#!/bin/sh

### Use this command to remove any orphaned files or dependencies
  	# orphans="pacman -Rns $(pacman -Qqtd)"

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkf="touch" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	size="du -h" \
	ffmpeg="ffmpeg -hide_banner" \
	thes="dict -d moby-thesaurus" \
	ispeed="speedtest-cli --bytes --secure"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	q="exit" \
	cl="clear" \
	p="pacman" \
	y="yay" \
	z="zathura" \
	update="pacman -Syu --noconfirm ; yay -Syu --noconfirm" \
	btb="echo power on | bluetoothctl; sleep 2; echo connect 28:F0:33:DD:F1:B1 | bluetoothctl" \
	retroPalm="sxiv -abfs w /home/code/pic/gif/retro-palm.gif" \
	sxivShow="sxiv -abfs w " \
	KSP="rm /home/code/gms/KSP/PartDatabase.cfg & rm /home/code/gms/KSP/GameData/ModuleManager.ConfigCache & rm /home/code/gms/KSP/GameData/ModuleManager.ConfigSHA & /home/code/gms/KSP/KSP.x86_64" \
	KSP_Test="rm /home/code/gms/KSP_Test/PartDatabase.cfg & rm /home/code/gms/KSP_Test/GameData/ModuleManager.ConfigCache & rm /home/code/gms/KSP_Test/GameData/ModuleManager.ConfigSHA & /home/code/gms/KSP_Test/KSP.x86_64" \

# Shorten the commands needed to update websites
alias \
	syncifnot1then0='rsync -vrP --delete-after ~/web/ifnot1then0/ web@remote:/var/www/ifnot1then0' \
	synckitchen='rsync -vrP --delete-after ~/web/kitchen/ web@remote:/var/www/kitchen' \
	syncnickjackson='rsync -vrP --delete-after ~/web/nickjackson/ web@remote:/var/www/nickjackson' \

# Other aliases that maybe useful
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
